### ISSUE TITLE
There was an error: u'walking'

### ISSUE THREAD

**Issue by yundddd** [blech/moves-geojson#1]
I was testing the webapp on localhost. After auth was successful, the /list page says 
There was an error: u'walking'

**Comment by yundddd** [comment]
It looks like a key mismatch. Maybe Moves changed their API? The returned summary dictionary has different keys now. Also, there is something wrong with the date format....Could you update on this? moves.husk.org still works though.

**Comment by bilal-karim** [comment]
How did you solve this issue? I'm getting error for `u'car'`.
**Edit:** Updating lookup = {} with 'car', 'walking', etc. fixed it.

Still getting the date format error though.

**Comment by yundddd** [comment]
> How did you solve this issue

sorry its been two years I hardly remember what this code does, let along fixing this problem. This issue was open for a long time and it looks like the owner is not maintaining it anymore.
